### ISSUE TITLE
Xtest: not able to run in wandboard

### ISSUE THREAD

**Issue by vvramya** [amarula/wiki-amarula#2]
Hi,

I have followed same procedure for wandboard(imx6q).
kernel is up and running fine. But i'm not able to run the xtest on the board.
Please help me to make it up.

Thanks,
Ramya

**Comment by mystictot** [comment]
Hi @vvramya,

Could you paste the error logs and please do enable the debugging.

**Comment by vvramya** [comment]
Hi @mysticTot ,
please find the attached screen shot for the xtest error.
![xtest_error_wandboard](https://user-images.githubusercontent.com/20204985/60482471-43126680-9caf-11e9-8c4b-f84998c5b852.png)
